version: "3.8"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: always
    container_name: hotf-website-prod
